---
# The org that will host the secure foundation
org_id: org_id

# Organization domain
org_domain: ""

# Where the secure foundation should be deployed. Will normally be the same as org, but may differ
# if for example it is to be installed in a sub folder
parent_id: "organizations/org_id"

# Names  for the new secure foundation
foundation_name: ""

# Billing account details
billing_account: ""
billing_admins: [""]
billing_creators: [""]
customer_id: ""

# Regions to be supported
default_region: "europe-west2"
other_regions:
  - "europe-west3"


# The secure foundation can set org level IAM if needed.
apply_org_priv: False

# List of Admins for this secure foundation. These users/group get owner priv on the secure
# foundation.  If "apply_org_priv" is true they will also get orgAdmin on the org
super_admins:
  - "user:"

# An email address for recieving Google support access requests
admin_notifications:
  - ""

# Location of this (github) repository so that cloud build can access it
# Only include the username/reponame
#   for example github.com/joeheaton/test becomes joeheaton/test
repo_location: "github_google_cloud"
repo_branch: "dev"
tenant_repo_location: "github_google_cloud"

# Billing logs are not alwarys required. Especially when multiple foundations are deployed
make_billing_logs: True
billing_log_owners: ["user:"]
billing_log_readers: []

# The secure fondation deploys initial infra and   s the setting
# below set the project labels to be applied to these elements
sf_infra_labels:
  environment: "bootstrap"
  application_name: "foundation"
  billing_code: "1234"
  primary_contact: "example1"
  secondary_contact: "example2"
  business_code: "abcd"

# The following enviroments will be created. "common" is always addeded by default
env_folder_names:
  - "prod"
  - "dev"
